import { StyleSheet, Dimensions } from "react-native";
const width = Dimensions.get("window").width;
const height = Dimensions.get("window").height;
import { colors } from "../../common/colors";
export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    padding: 25,
    borderWidth: 1,
    color: colors.primaryTextColor,
    backgroundColor: "yellow",
  },
  inputToolbarContainer: {
    backgroundColor: colors.white,
    alignContent: "center",
    justifyContent: "center",
    borderWidth: 0,
    paddingTop: 6,
    marginHorizontal: 6,
    borderRadius: 32,
    borderTopColor: "transparent",
    color: colors.primaryTextColor,
  },
  root: {
    backgroundColor: "#fff",
    flex: 1,
    padding: 20,
  },
  inputField: {
    marginBottom: 10,
    flexDirection: "column",
    paddingHorizontal: 20,
  },
  videoContainer: {
    flex: 1,
    minHeight: 450,
    borderWidth: 1,
  },
  videos: {
    width: "100%",
    flex: 1,
    position: "relative",
    overflow: "hidden",

    borderRadius: 6,
  },
  localVideos: {
    height: 100,
    marginBottom: 10,
  },
  remoteVideos: {
    height: 400,
  },
  localVideo: {
    backgroundColor: "#f2f2f2",
    height: "100%",
    width: "100%",
  },
  remoteVideo: {
    backgroundColor: "#f2f2f2",
    height: "100%",
    width: "100%",
  },
  textColor: {
    color: "#fff",
  },
  btnContentReject: {
    alignItems: "center",
    backgroundColor: "red",
    marginTop: 5,
    borderRadius: 10,
    height: 50,
    justifyContent: "center",
    border: 1,
    flex: 1,
    margin: 5,
  },
  btnContentAccept: {
    alignItems: "center",
    backgroundColor: "green",
    marginTop: 5,
    borderRadius: 10,
    height: 50,
    justifyContent: "center",
    border: 1,
    flex: 1,
    margin: 5,
  },
  input: {
    height: 50,
    marginBottom: 10,
    color: "#000",
    borderWidth: 1,
    marginTop: 10,
  },
  callbuton: {
    backgroundColor: "red",
    width: 80,
    height: 80,
    justifyContent: "center",
    alignItems: "center",
    padding: 10,
    borderRadius: 100,
  },
  maincallbtndiv: {
    justifyContent: "center",
    alignItems: "center",
  },
  bottomCenter: {
    flex: 1,
    justifyContent: "flex-end",
    marginBottom: 30,
    alignItems: "center",
  },
  callnamebtn: {
    backgroundColor: "#e7e7e7",
    width: 100,
    height: 100,
    justifyContent: "center",
    alignItems: "center",
    padding: 10,
    borderRadius: 100,
  },
  callnamebtnText: {
    fontSize: 20,
    color: "#000",
  },
  mainContainer: {
    height: 70,
    flexDirection: "row",
    shadowColor: "black",
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    shadowOpacity: 0.2,
    elevation: 3,
    borderBottomWidth: 1,
    borderBottomColor: "gray",
  },
  iconContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  subTextContainer: {
    marginTop: 4,
    borderWidth: 0,
    width: "85%",
    flexDirection: "row",
  },
  subTextStyle: {
    color: "gray",
    fontSize: 12,
    marginLeft: 5,
  },
  active: {
    height: 15,
    backgroundColor: "gray",
    borderWidth: 0,
    width: 15,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 50,
  },
  inActive: {
    height: 15,
    backgroundColor: "gray",
    borderWidth: 0,
    width: 15,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 50,
  },
  avtarContainer: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
  },
});
